<?php
/** @var \Magento\Sales\Block\Order\Email\Items $block */
/** @var \Magento\Sales\Model\Order $_order */
/** @var \Magento\GiftMessage\Helper\Message $gmHelper */
?>

<?php
    /** @var \Wismolabs\Tracking\ViewModel\OrderItemViewModel $siViewModel */
    $oiViewModel = $block->getData('orderItemViewModel');
?>

<?php $_order = $block->getOrder() ?>
<?php $gmHelper = $oiViewModel->getGiftMessageHelper() ?>
<?php if ($_order): ?>
    <?=$oiViewModel->getTrackButtonHtml($_order);?>
    <?php $_items = $_order->getAllItems(); ?>
    <table class="email-items">
        <thead>
            <tr>
                <th class="item-info">
                    <?= $escaper->escapeHtml(__('Items')) ?>
                </th>
                <th class="item-qty">
                    <?= $escaper->escapeHtml(__('Qty')) ?>
                </th>
                <th class="item-price">
                    <?= $escaper->escapeHtml(__('Price')) ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($_items as $_item): ?>
            <?php if (!$_item->getParentItem()): ?>
                <tbody>
                    <?= $block->getItemHtml($_item) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
        <tfoot class="order-totals">
            <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
    <?php if ($gmHelper
            ->isMessagesAllowed('order', $_order, $_order->getStore())
        && $_order->getGiftMessageId()
    ): ?>
        <?php $_giftMessage = $gmHelper
            ->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage): ?>
            <br />
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= $escaper->escapeHtml(__('Gift Message for this Order')) ?></h3>
                        <strong><?= $escaper->escapeHtml(__('From:')) ?></strong>
                         <?= $escaper->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= $escaper->escapeHtml(__('To:')) ?></strong>
                         <?= $escaper->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= $escaper->escapeHtml(__('Message:')) ?></strong>
                        <br /><?= $escaper->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
